# Generated by Django 6.0 on 2025-12-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Описание элемента', max_length=300),
        ),
    ]
